# Generated by Django 5.0.3 on 2024-04-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('release_year', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=50)),
                ('main_cast', models.CharField(max_length=100)),
                ('movie_poster', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=50)),
                ('imdb', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
