# Generated by Django 5.0.3 on 2024-04-18 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieData', '0002_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdb',
            new_name='IMDB_rating',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='release_year',
            new_name='year_of_release',
        ),
    ]
